### ISSUE TITLE
How to use react-routes with cockpit-starter-kit

### ISSUE THREAD

**Issue by burner986** [cockpit-project/starter-kit#466]
Hello,

I want to be able to navigate multiple routes when writing a plugin. Unfortunately I cannot implement this because Cockpit seems to interfere. 

Here is the code:

```js
import cockpit from "cockpit";
import React from "react";
import { BrowserRouter as Router, Route, Switch } from "react-router-dom";

const _ = cockpit.gettext;

class DebugRouter extends Router {
    constructor(props) {
        super(props);
        console.log(
            "initial history is: ",
            JSON.stringify(this.history, null, 2)
        );
        this.history.listen((location, action) => {
            console.log(
                `The current URL is ${location.pathname}${location.search}${location.hash}`
            );
            console.log(
                `The last navigation action was ${action}`,
                JSON.stringify(this.history, null, 2)
            );
        });
    }
}

export class Application extends React.Component {
    constructor() {
        super();
        this.state = {
            hostname: _("Unknown")
        };

        cockpit.file("/etc/hostname").watch((content) => {
            this.setState({ hostname: content.trim() });
        });
    }

    render() {
        return (
            <DebugRouter>
                <Switch>
                    <Route exact path="/">
                        <div>Hello index-World</div>
                    </Route>
                    <Route path="/create">
                        <div>Hello create-World</div>
                    </Route>
                    <Route path="/edit">
                        <div>Hello edit-World</div>
                    </Route>
                </Switch>
            </DebugRouter>
        );
    }
}
```

What I would expect is that when I call my plugins url then it will show index and when I navigate plugins-url/create or plugins-url/edit it would show the other text. However it doesn't show the text. In the log i can see these:

When I log the identified url then it shows this:
```
/cockpit/@localhost/dist/index.html
```

when I open /cockpit/dist/create in my browser then it logs this:
index.js:25 GET https://localhost:9090/cockpit/@localhost/dist/create.html 404 (Not Found)

I assume that cockpit is managing URLs in a different way and react-router-dom cannot be used. Am I right? If so, then how would I offer multiple pages within my plugin?

**Comment by martinpitt** [comment]
I suppose "In the log i can see these" was supposed to be followed by an actual log, but there is none. But I guess you will only be able to see the / top-level route. Indeed cockpit's web server will translate/look up an URL like /page/create , it has no idea that some parent component manages the route. At least at the moment, a route has to correspond to some [package manifest](https://cockpit-project.org/guide/latest/packages.html#package-manifest).

Cockpit pages handle sub-pages through the "hash" portion of the URL instead of sub-paths, like http://localhost:9090/system/services#/dbus.service or http://localhost:9090/users#/mpitt .  The [cockpit.location](https://cockpit-project.org/guide/latest/cockpit-location.html) API can be used for this.

I am not at all familiar with react-router, but apparently it has a `HashRouter` as well, which may work better?

**Comment by burner986** [comment]
Thanks for the info about HashRouter. With that it does work good enough
