### ISSUE TITLE
Usage of Cockpit-Components in lib-folder

### ISSUE THREAD

**Issue by burner986** [cockpit-project/starter-kit#469]
Hello,

it's me again with another question. I noticed that there's a lib folder within the src folder and in this folder there are several cockpit components. Are they intended to being used by plugin developers? I ask because I tried out the dialog component and ran into some issues which I want to describe:

I imported the dialog component
```
import { show_modal_dialog } from "./lib/cockpit-components-dialog.jsx";
```

This will give a build-error but was easily corrected by adding ./ to the paths like the error message suggested
```
ERROR in ./src/lib/cockpit-components-dialog.jsx 25:0-19
Module not found: Error: Can't resolve 'page.scss' in 'C:\Users\cyantis\Code\starterkit\src\lib'
Did you mean './page.scss'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (C:\Users\cyantis\Code\starterkit\node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

ERROR in ./src/lib/cockpit-components-dialog.jsx 26:0-39
Module not found: Error: Can't resolve 'cockpit-components-dialog.css' in 'C:\Users\cyantis\Code\starterkit\src\lib'
Did you mean './cockpit-components-dialog.css'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (C:\Users\cyantis\Code\starterkit\node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
```

Then I could use the dialog component but with the problem that there was no more vertical scrollbar and vertical scrolling became impossible. I fixed that by uncommenting these lines in the /lib/page.scss
```
// Let PF4 handle the scrolling through page component otherwise we might get double scrollbar
html:not(.index-page) body {
  overflow-y: hidden;

  // Ensure UI fills the entire page (and does not run over)
  .ct-page-fill {
    height: 100% !important;
  }
}
```

So now the dialog component seems to work fine for me but because of these issues and that I couldn't find a mentioning in any docs (or maybe I didn't find it) I am wondering if these should be used or rather not.

**Comment by martinpitt** [comment]
> Are they intended to being used by plugin developers? 

In general yes, but there are no API guarantees. Our standalone projects [check out a specific tag of cockpit's pkg/lib](https://github.com/cockpit-project/starter-kit/blob/master/Makefile#L154), and occasionally code or CSS has to be adjusted to newer versions. We find this the right balance of sharing code between cockpit pages.

You need to add the cloned lib dir to webpack's search path, like [here](https://github.com/cockpit-project/starter-kit/blob/master/webpack.config.js#L57). Then you also don't need to add the `./` everywhere.

That said, I wouldn't mind fixing cockpit's pkg/lib/ to always use relative import paths, so that this wouldn't be strictly necessary.
