### ISSUE TITLE
Question about packaging (Fedora Packaging Guidelines)

### ISSUE THREAD

**Issue by f1yn** [cockpit-project/starter-kit#823]
### Hey there!

I've been wanting to develop some cockpit plugins for a while now (I have two in the prototyping phase, and another one planned for later). I found this project, and it ended up using some tooling and processes I'm not fully familiar with.

> If you're short on time, feel free to skip to **Here's my questions** near the bottom:

As a result of this, I created a tangential starting project called [**cockpit-ultralight**](https://github.com/f1yn/cockpit-ultralight), which is comparatively more centred around people like me, who are Web developers foremost, and Linux System Administrators as a secondary skill-set. It's helped me become more familiar with the cockpit client code.

> Not that this is meant to be a plug, but feel free to check it out if you'd like - there's some really nice QoL features that may or may be not be nice to have here as well (live reloading, more typedefs, build and loading optimizations).

I'm at the point now where I'm wanting to roll packages, but as someone who has config file anxiety, I've been hoping to stay away from more CI/CD integration and roll my own podman scripts that take the production code, and then roll that into a distributable that copies it to the correct `/usr` directory when installed. While working on them, I've been going over the rpm/Fedora documentation for creating packages for release, and these sections stood out to me specifically:

https://docs.fedoraproject.org/en-US/packaging-guidelines/what-can-be-packaged/#prebuilt-binaries-or-libraries
> Summary: Pre-built code should not be ever used in re-distributable, as it's problematic for security.

There's a few things in the packaging documentation that says exceptions can be made, but this is confusing to me as cockpit plugins, by nature, are pretty platform agnostic. When broken down, it's essentially just meant to copy the end result from `/etc/`?

I'm very new to rolling binaries. I've had experiencing unrolling distributables, but going in the opposite direction is feeling a bit of a mess for me and I'd appreciate some guidance if you have a moment.

### Here's my questions:
1. While a single copy of web assets could be easily distributed (regardless of arch), having to also couple things to nodejs within the build script seems like a sure way to limit how far I can send a package. Is this the case? I'd prefer using `noarch` and just having bash copy the dist to the `/usr` dir - which is a huge part of the mental resistance. I don't think the Fedora project (or it's downstream) would be okay with that, but fundamentally that's what this feels like.

2. Is the package spec more aligned with a Makefile than I previously thought? More about how to make and create the source, end-to-end, than it is concerned with what's inside?

3. What's the cockpit plugin approval process look like (from a RHEL/Fedora perspective)? There's a lot of friction points within the Fedora Packaging Guidelines that make it look like heresy to not have build steps within in the spec. This could be collateral from coming from a profession where it goes source -> squash -> send.

Regardless of your answers, I'd still use podman to roll things, but there's some gaps in my knowledge about wrapping things up this way.

**Comment by martinpitt** [comment]
> > If you're short on time, feel free to skip to Here's my questions near the bottom:

Where is that from, out of interest? It's not the Fedora packaging guidelines or starter-kit.

> [... pre-built code ...] When broken down, it's essentially just meant to copy the end result from `/etc/`?

I suppose you meant "from dist/ to /usr/share/cockpit/"? Then yes. If you *did* mean `/etc`, then I don't understand this. sarter-kit and friends, all projects except cockpit itself (due to its webserver)  don't install anything in to /etc.

Indeed the Fedora packaging guidelines don't bless the pre-built dist/ bundles from upstream release tarballs, that's why starter-kit and cockpit-certificates srpms actually bundle the node_modules/ tree (in a separate `node-*` source) and rebuild dist/ during RPM build. It gives bitwise identical results to the upstream releases, so for the most part it's just wasted resources -- but it gives the warm fuzzy feeling of being able to patch the HTML/JS in downstream packages. For historical (and also efficiency) reasons, cockpit, c-machines and c-podman don't do this.

> While a single copy of web assets could be easily distributed (regardless of arch), having to also couple things to nodejs within the build script seems like a sure way to limit how far I can send a package

I'm not sure I understand this -- do you mean for size reasons (node_modules tarball is *biiiiiiig*), or licensing reasons (there's a lot more build deps and thus more licenses than the runtime dependencies).

> Is the package spec more aligned with a Makefile than I previously thought? More about how to make and create the source, end-to-end, than it is concerned with what's inside?

I can't answer this, I don't know what you thought :grin: But in general the spec should not make too many assumptions about the details of the Makefile -- just that running `make` will build the project.

> What's the cockpit plugin approval process look like

Pretty much the packaging guidelines.  Just that it's been quite a long time since we introduced a new cockpit package into Fedora. If we were to do it today, it most certainly had to use the starter-kit approach of rebuilding dist/ during package build -- not the old "just copy dist to /usr" quick and efficient way of cockpit.

**Comment by f1yn** [comment]
> I suppose you meant "from dist/ to /usr/share/cockpit/"? Then yes. If you did mean /etc, then I don't understand this. sarter-kit and friends, all projects except cockpit itself (due to its webserver) don't install anything in to /etc.

Whoops. Yeah, you are correct. I did mean `/usr` (not `/etc`).

> Indeed the Fedora packaging guidelines don't bless the pre-built dist/ bundles from upstream release tarballs, that's why starter-kit and cockpit-certificates srpms actually bundle the node_modules/ tree (in a separate node-* source) and rebuild dist/ during RPM build. It gives bitwise identical results to the upstream releases, so for the most part it's just wasted resources -- but it gives the warm fuzzy feeling of being able to patch the HTML/JS in downstream packages. For historical (and also efficiency) reasons, cockpit, c-machines and c-podman don't do this.

That sounds like the nightmare I wanted to avoid, specifically. Sounds like there's some reasons for the madness. I'll look into the cockpit-podman build, as there's a potential I can leverage that instead.

> > While a single copy of web assets could be easily distributed (regardless of arch), having to also couple things to nodejs within the build script seems like a sure way to limit how far I can send a package
>
> I'm not sure I understand this -- do you mean for size reasons (node_modules tarball is biiiiiiig), or licensing reasons (there's a lot more build deps and thus more licenses than the runtime dependencies).

I'm very new to build specs, but on paper, there's a point where you can specify the `BuildArch` of the spec, which, for something like web assets (which is inherently platform agnostic) would be `noarch`. Having a build requirement of `nodejs` would mean that I'd only be able to compile releases for arches that support it (which is not everything), which is why I asked.

> > While a single copy of web assets could be easily distributed (regardless of arch), having to also couple things to nodejs within the build script seems like a sure way to limit how far I can send a package
> 
> I'm not sure I understand this -- do you mean for size reasons (node_modules tarball is biiiiiiig), or licensing reasons (there's a lot more build deps and thus more licenses than the runtime dependencies).

Related to my above comment, but just to extend it with an example. A minified dist bundle is just Javascript, which, on paper could be served to any install with any arch (as long as they have `cockpit-bridge`). `nodejs` is not nearly as multiarch ([here's a Koji build that shows it's limited arches](https://koji.fedoraproject.org/koji/buildinfo?buildID=2424330)) - but [this seems to line up with the needs of the `cockpit` build  anyways](https://koji.fedoraproject.org/koji/buildinfo?buildID=2420207), so I suppose that's fine.

---

I think the takeaway from this is that Fedora (and likely Ubuntu/Debian) builds are not going to align with the _"copy dist to `/usr`"_ two line install I had in my head 😂. I'm guessing this is why the Applications menu was devised on cockpit, as that's much easier.

**Comment by martinpitt** [comment]
Note that the "copy dist/ to /usr" is what *actually* happens in the Debian/Ubuntu packages, and also all currently existing Fedora packages (due to "grandfathering", apparently just nobody looked that closely when these packages got introduced). So you can totally do it and avoid the nodejs build dep and huge node_modules tarball hassle. That will just start once you try to actually introduce your project into Fedora, but as long as it's in COPR/flathub/whereever else, it's fine :grin: 

The copy approach works well for us as Cockpit team, as we *never* patch downstream packages. We fix bugs upstream and create/package new releases, so that they get proper CI.
