### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by TanguyRaufflet** [cockpit-project/starter-kit#857]
Hello,

I have a question regarding the license for a cockpit plugins I plan to develop. The GPL license, indicates that "A main program that is separate from its plug-ins makes no requirements for the plug-ins".
So, if I am right, I should be able to put the license Apache 2.0 on it. But, the starter-kit you provide is under LGPL 2.1. Then, all the projects based on it will need to be LGPL 2.1 compatible.
Is it something you considered when choosing the license for the Starter-Kit ?

**Comment by martinpitt** [comment]
We did consider it, mostly because all other Cockpit projects are under LGPL, and we like the GPL. But as you say, Cockpit's own license does not apply to third-party plugins, so if you create your own, you can pick any license you want.

But the actual source code that applies to the runtime of the plugin in starter-kit is utterly trivial, e.g. https://github.com/cockpit-project/starter-kit/blob/main/src/app.jsx . You'll have to replace all significant bits with "real" code anyway, so there's not much left in the file -- in other words, just start from a fresh file and treat it as documentation.

The same applies to the [tests](https://github.com/cockpit-project/starter-kit/blob/main/test/check-application) -- they show you how to do it, but you'll have to replace all the actual code anyway.

So, feel free to pick a different license for your own project.
